# dev-jenkins-rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-deployer-rolebinding
  namespace: dev
subjects:
- kind: ServiceAccount
  name: jenkins-deployer
  namespace: dev
roleRef:
  kind: Role
  name: jenkins-deployer-role
  apiGroup: rbac.authorization.k8s.io
