# jenkins-deployer-portforward-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-deployer-portforward
  namespace: dev
rules:
- apiGroups: [""]
  resources: ["pods/portforward"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-deployer-portforward-binding
  namespace: dev
subjects:
- kind: ServiceAccount
  name: jenkins-deployer
  namespace: dev
roleRef:
  kind: Role
  name: jenkins-deployer-portforward
  apiGroup: rbac.authorization.k8s.io
