apiVersion: v1
kind: ingress
metadata:
  name: sample-app-ingress
  annotations:
    kubernetes.io/ingress.class: nginx  
  labels:
    app.Kubernetes.io/name: sample-app  
    app.Kubernetes.io/instance: sample-app-instance
spec:
  rules:
    - host: sample-app.local
      http:
        paths:
           - path: /
             pathType: Prefix
             backend:
              service:
                name: sample-app-service
                port:
                  number: 8080